name: deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm ci && npm run build
      - run: rm -rf node_modules/ && npm ci --production
      - run: zip -r deployment.zip node_modules/
      - run: cd app && zip -r ../deployment.zip *
      - name: deploy server to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: roubleratebot-server
          zip_file: ./deployment.zip
          handler: server.handler
      - name: deploy loader to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: roubleratebot-loader
          zip_file: ./deployment.zip
          handler: loader.handler